name: Daily Model Training

on:
  schedule:
    # Run every day at 3 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering
    inputs:
      force_retrain:
        description: 'Force retrain all models'
        required: false
        default: false
        type: boolean

jobs:
  train-models:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests python-dotenv supabase
        
    - name: Get all users and train models
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        HUGGINGFACE_SPACE_URL: ${{ secrets.HUGGINGFACE_SPACE_URL }}  # e.g., https://your-space.hf.space
        SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}  # For auth bypass
        FORCE_RETRAIN: ${{ github.event.inputs.force_retrain || 'false' }}
      run: |
        # Try to run from backend/spaces first, fallback to root
        if [ -f "backend/spaces/github_train_all.py" ]; then
          echo "🔍 Running script from backend/spaces/"
          cd backend/spaces
          python github_train_all.py
        elif [ -f "github_train_all.py" ]; then
          echo "🔍 Running script from root directory"
          python github_train_all.py
        else
          echo "❌ GitHub training script not found!"
          exit 1
        fi
